hjjt-portal/HJJTPortal/HJJTPortal.UI/Controllers/ApplicationsController.cs
using HJJTPortal.UI.Models;
using Portal.BLL;
using Portal.Models;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace HJJTPortal.UI.Controllers
{
    public class CandidatesController : Controller
    {
        private Operations ops = new Operations();

        public ActionResult Index()
        {
            var candidates = ops.GetAllCandidates();
            return View(candidates);
        }

        public ActionResult Create()
        {
            var vm = new CandidateCreateVM();
            return View(vm);
        }

        [HttpPost]
        public ActionResult Create(Candidate model)
        {
            if (ModelState.IsValid)
            {
                var response = ops.CreateCandidate(model);
                if (response.Success)
                {
                    return RedirectToAction("AddWorkHistory", new { candidateid = model.CandidateId });
                }
                ModelState.AddModelError("", response.Message);
            }
            var vm = new CandidateCreateVM();
            return View(vm);
        }

        public ActionResult AddWorkHistory(int candidateid)
        {
            var model = new WorkHistory();
            model.CandidateId = candidateid;
            return View(model);
        }

        [HttpPost]
        public ActionResult AddWorkHistory(WorkHistory model)
        {
            if (Request.Form.AllKeys.Contains("Next"))
            {
                return RedirectToAction("AddEducationHistory", new { id = model.CandidateId });
            }
            if (ModelState.IsValid)
            {
                var response = ops.CreateWorkHistory(model);
                if (response.Success)
                {
                    ModelState.Clear();
                    int id = model.CandidateId;
                    model = new WorkHistory();
                    model.CandidateId = id;
                    return View(model);
                }
                ModelState.AddModelError("", response.Message);
            }
            return View(model);
        }

        [HttpPost]
        public ActionResult AddEducationHistory(EducationHistory model)
        {
            if (Request.Form.AllKeys.Contains("Next"))
            {
                return RedirectToAction("Index");
            }
            if (ModelState.IsValid)
            {
                var response = ops.CreateEducationHistory(model);
                if (response.Success)
                {
                    int id = model.CandidateId;
                    model = new EducationHistory();
                    model.CandidateId = id;
                    return View(model);
                }
                ModelState.AddModelError("", response.Message);
            }
            return View(model);
        }

        public ActionResult AddEducationHistory(int candidateid)
        {
            var model = new EducationHistory();
            model.CandidateId = candidateid;
            return View(model);
        }

        public ActionResult Review(int id)
        {
            var Model = new ReviewVM()
            {
                Candidate = ops.GetCandidateByID(id),
                DesiredJobInfo = ops.GetDesiredJobInfoByID(id),
                WorkHistory = ops.GetHistoryByID(id),
                EducationHistory = ops.GetEducationHistoryByID(id)
            };
            return View(Model);
        }
    }
}

hjjt-portal/HJJTPortal/HJJTPortal.UI/Controllers/HomeController.cs
using HJJTPortal.UI.Models;
using Portal.BLL;
using Portal.Data;
using Portal.Data.Interfaces;
using Portal.Data.Policies;
using Portal.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace HJJTPortal.UI.Controllers
{
    public class HomeController : Controller
    {
        private Operations ops = new Operations();

        public HomeController()
        {
        }

        // GET: Home
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Careers()
        {
            return View();
        }

        //public ActionResult Application()
        //{
        //    return View(new Candidate());
        //}

        //[HttpPost]
        //public ActionResult Application(Candidate candidate)
        //{
        //    if (candidate.PhoneNumber.Length != 12)
        //    {
        //        ModelState.AddModelError("PhoneNumber", "Please enter a valid phone number");
        //    }

        //    if (DateTime.Now.Year - candidate.BirthDate.Year < 16)
        //    {
        //        ModelState.AddModelError("Birthdate", "You must be at least 16");
        //    }

        //    if (ModelState.IsValid)
        //    {
        //        ops.CreateCandidate(candidate);
        //        return RedirectToAction("EduHx", new { id = candidate.CandidateId });
        //    }
        //    return View();
        //}

        //public ActionResult EduHx(int id)
        //{
        //    var model = new EducationHistoryVM()
        //    {
        //        EducationHistories = new List<EducationHistory>()
        //        {
        //            new EducationHistory()
        //            {
        //                CandidateId = id
        //            }
        //        }
        //    };
        //    model.id = id;

        //    if (ops.GetHistoryByID(id).Count > 0)
        //    {
        //        model.EducationHistories = ops.GetEducationHistoryByID(id);
        //    }
        //    return View(model);
        //}

        //[HttpPost]
        //public ActionResult EduHx(List<EducationHistory> educationHx)
        //{
        //    if (Request.Form.AllKeys.Contains("Next"))
        //    {
        //        if (ModelState.IsValid && ops.GetHistoryByID(educationHx[0].CandidateId) != null)
        //        {
        //            return RedirectToAction("Review", new { id = educationHx[0].CandidateId });
        //        }

        //        if (ModelState.IsValid)
        //        {
        //            // ops.CreateEducationHistory(educationHx);
        //            return RedirectToAction("WorkHx", new { id = educationHx[0].CandidateId });
        //        }
        //    }
        //    else if (Request.Form.AllKeys.Contains("Add"))
        //    {
        //        educationHx.Add(new EducationHistory());

        //        var model = new EducationHistoryVM()
        //        {
        //            EducationHistories = educationHx,
        //        };

        //        return View(model);
        //    }
        //    return View();
        //}

        //public ActionResult WorkHx(int id)
        //{
        //    var model = new WorkHistoryVM();
        //    model.id = id;
        //    return View(model);
        //}

        //[HttpPost]
        //public ActionResult WorkHx(List<WorkHistory> workHistories)
        //{
        //    foreach (var workHistory in workHistories)
        //    {
        //        if (workHistory.CurrentlyWorking == true && workHistory.EndDate != null)
        //        {
        //            ModelState.AddModelError("EndDate", "Current job can't have an end date");
        //        }

        //        if (workHistory.CurrentlyWorking == false && workHistory.EndDate == null)
        //        {
        //            ModelState.AddModelError("EndDate", "Previous job must have an end date");
        //        }
        //    }
        //    if (ModelState.IsValid)
        //    {
        //        //ops.CreateWorkHistory(workHistories);
        //        return RedirectToAction("DesiredJobInfo", new { id = workHistories[0].CandidateId });
        //    }

        //    return View();
        //}

        //public ActionResult DesiredJobInfo(int id)
        //{
        //    var model = new JobsVM();
        //    return View(model);
        //}

        //[HttpPost]
        //public ActionResult DesiredJobInfo(DesiredJobInfo djInfo)
        //{
        //    ops.CreateDesiredJobInfo(djInfo);
        //    return RedirectToAction("Review", new { id = djInfo.CandidateId });
        //}

        //public ActionResult Review(int id)
        //{
        //    var Model = new ReviewVM()
        //    {
        //        Candidate = ops.GetCandidateByID(id),
        //        DesiredJobInfo = ops.GetDesiredJobInfoByID(id),
        //        WorkHistory = ops.GetHistoryByID(id),
        //        EducationHistory = ops.GetEducationHistoryByID(id)
        //    };
        //    return View(Model);
        //}

        //public ActionResult Candidates()
        //{
        //    var _repo = RepoFactory.CreateCandidateRepository();
        //    return View(_repo.GetAll());
        //}

        public ActionResult Login()
        {
            return RedirectToAction("Login");
        }
    }
}

hjjt-portal/HJJTPortal/HJJTPortal.UI/Views/Home/Application.cshtml
@model Portal.Models.Candidate

@{
    ViewBag.Title = "Application";
}
@using (Html.BeginForm("Application", "Home", FormMethod.Post))
{
    @Html.AntiForgeryToken()
    <h2>Application</h2>
    <fieldset>

        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            <label class="col-lg-2 control-label">First Name</label>
            <div class="col-lg-10">
                @Html.EditorFor(m => m.FirstName, new { @class = "form-control" })
                @Html.ValidationMessageFor(m => m.FirstName, "", new { @class = "text-danger" })
                @*<input type="text" name="FirstName" class="form-control">*@
            </div>
        </div>
        <div class="form-group">
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <label class="col-lg-2 control-label">Last Name</label>
            <div class="col-lg-10">
                @Html.EditorFor(m => m.LastName, new { @class = "form-control" })
                @Html.ValidationMessageFor(m => m.LastName, "", new { @class = "text-danger" })
                @*<input type="text" name="LastName" class="form-control">*@
            </div>
        </div>
        <div class="form-group">
            <label class="col-lg-2 control-label">Email</label>
            <div class="col-lg-10">
                @Html.EditorFor(m => m.EMail, new { @class = "form-control" })
                @Html.ValidationMessageFor(m => m.EMail, "", new { @class = "text-danger" })
                @*<input type="text" name="EMail"class="form-control" placeholder="Email">*@
            </div>
        </div>
        <div class="form-group">
            <label class="col-lg-2 control-label">Address</label>
            <div class="col-lg-10">
                @Html.EditorFor(m => m.Address.Street, new { @class = "form-control" })
                @Html.ValidationMessageFor(m => m.Address.Street, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <label class="col-lg-2 control-label">City</label>
            <div class="col-lg-10">
                @Html.EditorFor(m => m.Address.City, new { @class = "form-control" })
                @Html.ValidationMessageFor(m => m.Address.City, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <label class="col-lg-2 control-label">State</label>
            <div class="col-lg-10">
                @Html.EditorFor(m => m.Address.State, new { @class = "form-control" })
                @Html.ValidationMessageFor(m => m.Address.State, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <label class="col-lg-2 control-label">Zip Code</label>
            <div class="col-lg-10">
                @Html.EditorFor(m => m.Address.Zipcode, new { @class = "form-control" })
                @Html.ValidationMessageFor(m => m.Address.Zipcode, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <label class="col-lg-2 control-label">Phone Number</label>
            <div class="col-lg-10">
                @Html.EditorFor(m => m.PhoneNumber, new { @class = "form-control", @placeholder = "xxx-xxx-xxxx" })
                @Html.ValidationMessageFor(m => m.PhoneNumber, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <label class="col-lg-2 control-label">Birth Date</label>
            <div class="col-lg-10">
                @Html.EditorFor(m => m.BirthDate, new { @class = "form-control" })
                @Html.ValidationMessageFor(m => m.BirthDate, "", new { @class = "text-danger" })
            </div>
        </div>
        <p></p>
        <p></p>
        <div class="form-group">
            <div class="col-lg-10 col-lg-offset-2">
                <button type="reset" class="btn btn-default">Cancel</button>
                <button type="submit" href="EducationHistory" class="btn btn-primary">Next</button>
            </div>
        </div>
    </fieldset>

        @Html.ActionLink("Back to List", "Index")

}

hjjt-portal/HJJTPortal/HJJTPortal.UI/Views/Home/Careers.cshtml
@{
    ViewBag.Title = "Careers";
}

<h2>Careers</h2>

<p style="text-align: center"><a style="color: red; font-size: large;" href="@Url.Action("Create", "Candidates")">APPLY NOW!       </a><img src="../../Content/PICS/apply.jpg" alt="applynow" align="middle" style="border: solid 2px darkgrey;"></p>

hjjt-portal/HJJTPortal/HJJTPortal.UI/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Index";
}
<div class="jumbotron" style="text-align: center; margin: auto;">
    <h4>Welcome to Cena Consulting LLC.</h4>
    <audio id="Intro">
        <source src="~/Content/intro.mp3" />
    </audio>
    <img src="~/Content/PICS/john_cena00.jpg" size="242px;" style="border: 2px darkgrey solid;" onclick="document.getElementById('Intro').play()" />
    <h5>"Where YOU are the CHAMP here."</h5>
</div>